### ISSUE TITLE
FRUS1949v05

### ISSUE THREAD

**Issue by vak2ve** [joewiz/frus-tei#29] opened 2014-11-25 20:04 UTC
- [x] Passes FRUS TEI Schematron check
- [x] Passes RelaxNG schema check
- [x] Commit schema-compliant file to SVN
- [x] Upload the FRUS TEI file into localhost
- [x] Upload page images to S3
- [x] Typography and characters
- [x] Source note coding
- [x] Table of contents
- [ ] Front matter
- [x] Back matter
- [x] Random sample
- [x] Volume metadata

**Comment by joewiz** [comment] 2015-01-23 20:25
@vak2ve The issue is that the `<term>` and `<hi>` elements are appearing in essentially reverse order.  In FRUS persons and terms list, the trailing comma that marks the end of the person/term being described is also bold.  

![screen shot 2015-01-23 at 3 18 59 pm](https://cloud.githubusercontent.com/assets/59118/5881953/4d77295c-a313-11e4-8116-0c1732638a4a.png)

The correct way to capture this is (adding extra indenting for clarity here):

```xml
<item>
    <hi rend="strong">
        <term xml:id="t_ACR1">ACR</term>, 
    </hi> 
    Advisory Committee on Requirements
</item>
```

Instead, in this volume, the placement of hi is inside the term, as follows:

```xml
<item>
    <term xml:id="t_ACR1">
        <hi rend="strong">ACR</hi>,
    </term> 
    Advisory Committee on Requirements
</item>
```

Since our site assumes the former structure, it mangles the display of the latter.  We should probably return these volumes to HCL to correct.  Could you please assemble the list of affected volumes?  This is probably also an opportunity for a schematron rule to check for this problem.  Good catch, thanks!

**Comment by vak2ve** [comment] 2015-01-24 00:20
This was a huge global error--see most recent commit for all files affected. They're fine now (relatively quick fix) but definitely something to communicate to HCL for the future.

**Comment by joewiz** [comment] 2015-04-08 19:29
Is this one all set now, or are there any remaining issues?

**Comment by vak2ve** [comment] 2015-04-08 20:04
Yes, this and Malta should be good to go now!

**Comment by joewiz** [comment] 2015-04-09 13:59
Okay, I assume that one remaining checkbox is actually done, so I'll go ahead and close the issue. Thanks!

**Closed by joewiz** 2015-04-09 13:59 UTC
